---
# Resourceの定義
resources:
# Git Resourceの定義
- name: hello
  type: git
  source:
    uri: https://github.com/nishida-actx/hello-concourse.git
- name: result
  type: git
  source:
    uri: git@gist.github.com:d85996771a2dc1eaebf46d03c1d75cfb.git
    private_key: {{github-private-key}}
    branch: master 
# Jobの定義
jobs:
- name: hello-job
  public: true # UI上でJobの結果をログイン不要で公開するかどうか
  plan:
  - get: hello
    trigger: true # Resourceに変更があれば自動でジョブを実行するかどうか
  - get: result
  - task: run-hello
    file: hello/hello.yml
  - task: commit-log
    file: hello/commit-log.yml
  - put: result
    params:
      repository: updated-result
